apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-logpull-exporter
  labels:
    app.kubernetes.io/name: cloudflare-logpull-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-logpull-exporter
  endpoints:
    - port: metrics
