apiVersion: v1
kind: Service
metadata:
  name: cloudflare-logpull-exporter
  labels:
    app.kubernetes.io/name: cloudflare-logpull-exporter
spec:
  selector:
    app.kubernetes.io/name: cloudflare-logpull-exporter
  ports:
  - name: metrics
    port: 9299
